CREATE TABLE furniture.PICTURE ( 
PICTURE_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
PICTURE_TYPE_CODE VARCHAR(255), 
CAPTION VARCHAR(255),
DESCRIPTION VARCHAR(255),
IMG LONGBLOB, 
THUMB LONGBLOB, 
PRIMARY KEY(PICTURE_ID) 
);