package com.furniture.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Actor implements Serializable {

	private static final long serialVersionUID = 2867868819352971925L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column actor.actor_id
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    private Short actorId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column actor.first_name
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    private String firstName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column actor.last_name
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    private String lastName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column actor.last_update
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    private Date lastUpdate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column actor.actor_id
     *
     * @return the value of actor.actor_id
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public Short getActorId() {
        return actorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column actor.actor_id
     *
     * @param actorId the value for actor.actor_id
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public void setActorId(Short actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column actor.first_name
     *
     * @return the value of actor.first_name
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column actor.first_name
     *
     * @param firstName the value for actor.first_name
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column actor.last_name
     *
     * @return the value of actor.last_name
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column actor.last_name
     *
     * @param lastName the value for actor.last_name
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column actor.last_update
     *
     * @return the value of actor.last_update
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column actor.last_update
     *
     * @param lastUpdate the value for actor.last_update
     *
     * @ibatorgenerated Wed Aug 27 18:17:53 EDT 2014
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}