package com.furniture.persistence.model;

import java.io.Serializable;

public class Picture implements Serializable {

	private static final long serialVersionUID = 3748101808784183958L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column picture.PICTURE_ID
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    private Integer pictureId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column picture.PICTURE_TYPE_CODE
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    private String pictureTypeCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column picture.CAPTION
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    private String caption;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column picture.DESCRIPTION
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column picture.IMG
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    private byte[] img;

    private byte[] thumb;
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column picture.PICTURE_ID
     *
     * @return the value of picture.PICTURE_ID
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public Integer getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column picture.PICTURE_ID
     *
     * @param pictureId the value for picture.PICTURE_ID
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column picture.PICTURE_TYPE_CODE
     *
     * @return the value of picture.PICTURE_TYPE_CODE
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public String getPictureTypeCode() {
        return pictureTypeCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column picture.PICTURE_TYPE_CODE
     *
     * @param pictureTypeCode the value for picture.PICTURE_TYPE_CODE
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public void setPictureTypeCode(String pictureTypeCode) {
        this.pictureTypeCode = pictureTypeCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column picture.CAPTION
     *
     * @return the value of picture.CAPTION
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column picture.CAPTION
     *
     * @param caption the value for picture.CAPTION
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public void setCaption(String caption) {
        this.caption = caption;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column picture.DESCRIPTION
     *
     * @return the value of picture.DESCRIPTION
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column picture.DESCRIPTION
     *
     * @param description the value for picture.DESCRIPTION
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column picture.IMG
     *
     * @return the value of picture.IMG
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public byte[] getImg() {
        return img;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column picture.IMG
     *
     * @param img the value for picture.IMG
     *
     * @ibatorgenerated Sun Aug 31 14:56:02 EDT 2014
     */
    public void setImg(byte[] img) {
        this.img = img;
    }

	public byte[] getThumb() {
		return thumb;
	}

	public void setThumb(byte[] thumb) {
		this.thumb = thumb;
	}
}